version: '3.8'

services:
  aws:
    environment:
      DEBUG: 1
      LAMBDA_DOCKER_NETWORK: aws-network
      LAMBDA_REMOTE_DOCKER: 0
      SERVICES: lambda
    image: localstack/localstack:0.11.6
    networks:
      - aws-network
    ports:
      - 4566:4566
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  node-app:
    build: ./node-app
    environment:
      AWS_ACCESSKEY_ID: can-be-anything
      AWS_ACCESSKEY_SECRETKEY: can-be-anything
      AWS_ENDPOINT: aws:4566
      AWS_REGION: us-east-1
      NODE_ENV: development
    networks:
      - aws-network
    volumes:
      - ./node-app:/app

networks:
  aws-network:
    name: aws-network
